### PR TITLE
removed unwanted files from the project

### LINKED ISSUE #48: Cleaning Out Unwanted Files

### PR DESCRIPTION
**Pull request by shikhar13012001**
I have removed unwanted files as I saw fit , please review my PR and tell me if you want any changes, 
Thank you

### CODE REVIEW

**Comment by devanshuyadav** [comment]
@shikhar13012001 Can you pls deploy [your repository](https://github.com/shikhar13012001/helpage/tree/Clean_project) onto GitHub pages so that I can just have a good look at Its functioning before merging this PR.

**Comment by shikhar13012001** [comment]
> @shikhar13012001 Can you pls deploy [your repository](https://github.com/shikhar13012001/helpage/tree/Clean_project) onto GitHub pages so that I can just have a good look at Its functioning before merging this PR.

I have hosted it at [Netlify](https://modest-shaw-3553c5.netlify.app/), if that's not a problem 😅😅

**Comment by devanshuyadav** [comment]
@combe15 @light-200 @BinayakBishnu Please Verify that none of your files are deleted in this PR.

**Comment by combe15** [comment]
@devanshuyadav @shikhar13012001

the following is being used:
new_styles.scss - used for making CSS file
images/green-favicon.ico - used in index.html
images/helpageBrave.png - used in README.md
images/helpageChrome.png - used in README.md
images/helpageSafari.png  - used in README.md
images/home.ico - used in index.html

new_styles.css.map is autogenerated when newstyles.scss is used. so it's not logical to remove it unless you make a .gitignore file

All that being said, only images/favicon.ico and styles.css are not being used.

I would argue that new_styles.css should be renamed into styles.css and also reflect that change in index.html

**Comment by shikhar13012001** [comment]
> @devanshuyadav @shikhar13012001
> 
> the following is being used: new_styles.scss - used for making CSS file images/green-favicon.ico - used in index.html images/helpageBrave.png - used in README.md images/helpageChrome.png - used in README.md images/helpageSafari.png - used in README.md images/home.ico - used in index.html
> 
> new_styles.css.map is autogenerated when newstyles.scss is used. so it's not logical to remove it unless you make a .gitignore file
> 
> All that being said, only images/favicon.ico and styles.css are not being used.
> 
> I would argue that new_styles.css should be renamed into styles.css and also reflect that change in index.html

Ok sir I will those changes

**Comment by shikhar13012001** [comment]
@combe15 I have made the above changes please review the PR and let me know if you need any changes, thankyou.

**Review by combe15 — CHANGES_REQUESTED** [review]
.gitignore should be `*.map` as it's the map files that we are trying to filter out.

You will need to rename everything that has the name "new_styles" in order to match. this includes the .scss file.

**Comment by combe15** [comment]
Also, try to keep in the habit of writing descriptive commit messages. The purpose of the messages is to know specifically what you did WITHOUT having to look at the diff 😀

**Comment by shikhar13012001** [comment]
> Also, try to keep in the habit of writing descriptive commit messages. The purpose of the messages is to know specifically what you did WITHOUT having to look at the diff 😀

Sorry sir, I am a bit new to Open source, I will keep that in my mind next time, thankyou

**Review by combe15 — APPROVED** [review]
Looks good to me

**Comment by combe15** [comment]
> Sorry sir, I am a bit new to Open source, I will keep that in my mind next time, thankyou

It's all good! Everyone had to start somewhere.

**Review by devanshuyadav — APPROVED** [review]

**Pull request merged**
