### PR TITLE
feat: bookmark dark mode color, bg, animation

### PR DESCRIPTION
**Pull request by binayakbishnu**
The bookmark list in light and dark mode looked as if disabled due to the grey font-colour
Changed dark theme designs
- Font colour of members
- background and font-colour change on hover
- linespace animation on hover

Made styles into scss file and used live sass to create CSS files to include WebKit attributes automatically [to ensure compatibility in older browsers]
Styles copy-pasted from older styles.css and then edited for the above changes so all styles except those of bookmark are the same
The new styles file is new_styles.css
HTML refers to new_styles now
**Can go back to the old design by only changing the stylesheet link in <head>**

Will now work on the same design in the light theme.

@devanshuyadav

### CODE REVIEW

**Comment by devanshuyadav** [comment]
Hi @BinayakBishnu, The changes look fine to me & it has no conflicts too.
Could you deploy your forked repo (https://github.com/BinayakBishnu/helpage) onto GitHub pages, So I can preview the changes before merging onto the main project.

**Comment by binayakbishnu** [comment]
Sure 
I will share the link here

**Comment by binayakbishnu** [comment]
https://binayakbishnu.github.io/helpage/

Screenshot:
image

**Note: the changes are made only in dark mode. If you like the format, I will put similar edits in light mode too**
@devanshuyadav

**Comment by devanshuyadav** [comment]
Could you pls remove that growing animation in the bookmarks bar? It feels odd when the whole dropdown resizes due to overflowing text.

**Comment by binayakbishnu** [comment]
Ok will remove increase in letter spacing
Everything else is fine?

**Comment by binayakbishnu** [comment]
am closing this PR and making new one

**Pull request closed without merging**
