### PR TITLE
Changed initial theme to match system's preferences

### PR DESCRIPTION
**Pull request by combe15**
Changed default theme to match the browser's color scheme upon the first load.

If the browser prefers the dark theme, the website will use the dark theme. If the light theme is preferred, or no preference is given, the website will default to the light theme.

### CODE REVIEW

**Comment by devanshuyadav** [comment]
Hey @combe15, see if you could resolve the merge conflicts.

**Comment by combe15** [comment]
@devanshuyadav Fixed! Please mark this PR for Hacktoberfest!

**Comment by devanshuyadav** [comment]
Hey, @combe15 I can mark your PR for Hactober but it won't be counted since my repo isn't included in Hactoberfest.

**Comment by combe15** [comment]
> Hey, @combe15 I can mark your PR for Hactober but it won't be counted since my repo isn't included in Hactoberfest.

@devanshuyadav

Just to let you know, The fact you added the `hacktoberfest-accepted` label and that this repo has the hacktoberfest tag, means that this repo, is in fact, included in Hacktoberfest.

**Comment by devanshuyadav** [comment]
Is it updated on your Hacktoberfest Account?

**Comment by combe15** [comment]
Yes it is!

**Pull request merged**
